#!/usr/bin/env python3
"""
Generate a DQV-style Cypher enrichment script from data-profiling YAML files.

Usage:
    python generate_dqv_cypher.py [yaml_dir] [output_file]

    yaml_dir    - directory containing *__*__profile.yaml files (default: .)
    output_file - path for the output .cypher file (default: <yaml_dir>/dqv_profile.cypher)
"""

import sys
import os
import glob
import argparse
from datetime import datetime

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


# Ordered list of all metric field names recognised from profile YAMLs.
# top_values is intentionally excluded — distributions are kept in the YAML only.
KNOWN_METRICS = [
    "null_count",
    "null_rate",
    "distinct_count",
    "min",
    "max",
    "mean",
    "stddev",
    "percentile_25",
    "percentile_50",
    "percentile_75",
    "min_length",
    "max_length",
    "avg_length",
]


def esc(value: str) -> str:
    """Escape single quotes for Cypher string literals."""
    return str(value).replace("'", "\\'")


def cypher_value(v) -> str:
    """Format a Python value as a Cypher literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return f"'{esc(v)}'"
    if isinstance(v, float):
        return repr(v)
    return str(v)


def column_metrics(col: dict) -> list[tuple[str, object]]:
    """Return (metric_name, value) pairs for a column, preserving KNOWN_METRICS order."""
    return [
        (m, col[m])
        for m in KNOWN_METRICS
        if m in col and col[m] is not None
    ]


def load_profiles(yaml_dir: str) -> list[dict]:
    # Look in data_profiling/ subfolder first, fall back to yaml_dir itself
    profiling_subdir = os.path.join(yaml_dir, "data_profiling")
    search_dir = profiling_subdir if os.path.isdir(profiling_subdir) else yaml_dir

    pattern = os.path.join(search_dir, "*__*__profile.yaml")
    files = sorted(glob.glob(pattern))
    if not files:
        print(
            f"ERROR: No *__*__profile.yaml files found in '{search_dir}'.\n"
            "Run the data-profiling skill first.",
            file=sys.stderr,
        )
        sys.exit(1)

    profiles = []
    for f in files:
        with open(f) as fh:
            data = yaml.safe_load(fh)
        if data and "schema" in data and "table" in data:
            profiles.append(data)
        else:
            print(f"WARNING: Skipping '{f}' — missing 'schema' or 'table'.", file=sys.stderr)
    return profiles


def _uri(prefix: str, path: str, project_code: str | None = None) -> str:
    """Build a URI with optional project-code scoping."""
    if project_code:
        return f"{prefix}:{project_code}:{path}"
    return f"{prefix}:{path}"


def build_cypher(profiles: list[dict], project_code: str | None = None) -> tuple[list[str], dict]:
    stats = {"datasets": 0, "columns": 0, "measurements": 0, "top_value_nodes": 0}

    # Collect the superset of metrics actually present across all profiles
    metrics_used: list[str] = []
    seen: set[str] = set()
    for p in profiles:
        for col in p.get("columns") or []:
            for m_name, _ in column_metrics(col):
                if m_name not in seen:
                    metrics_used.append(m_name)
                    seen.add(m_name)

    lines = [
        "// DQV Profile Enrichment — Knowledge Graph",
        "// Ontology: https://www.w3.org/TR/vocab-dqv/",
        "// Generated by the data-profiling-to-dqv-neo4j Claude skill",
        f"// Generated at: {datetime.utcnow().replace(microsecond=0).isoformat()}",
    ]
    if project_code:
        lines.append(f"// Project: {project_code}")
    lines += [
        "",
        "// ── Metric nodes (dqv:Metric) — MERGE so re-runs are idempotent ─────────────",
    ]

    for m in metrics_used:
        lines.append(
            f"MERGE (:Metric {{uri: 'metric:{m}', name: '{m}', dcatType: 'dqv:Metric'}});"
        )
    lines.append("")

    pc = project_code
    for p in profiles:
        schema = p["schema"]
        table = p["table"]
        row_count = p.get("row_count", 0)
        sample_size = p.get("sample_size", row_count)
        profiled_at = p.get("profiled_at", "")
        dataset_uri = _uri("dataset", f"{schema}.{table}", pc)

        lines += [
            f"// === Table: {schema}.{table} ===",
            "",
            f"MATCH (ds:Dataset {{uri: '{dataset_uri}'}})",
            f"SET ds.row_count = {row_count}, ds.sample_size = {sample_size}, ds.profiled_at = '{profiled_at}';",
            "",
        ]
        stats["datasets"] += 1

        for col in p.get("columns") or []:
            col_name = col["name"]
            col_uri = _uri("column", f"{schema}.{table}.{col_name}", pc)
            metrics = column_metrics(col)
            if not metrics:
                continue

            stats["columns"] += 1

            # One statement per column: MATCH column + all required metric nodes,
            # then CREATE all QualityMeasurement nodes in the same clause.
            block = [f"// Column: {col_name}"]
            block.append(f"MATCH (col:Column {{uri: '{col_uri}'}})")

            vars_and_values: list[tuple[str, object]] = []
            for i, (m_name, m_val) in enumerate(metrics):
                var = f"m{i}"
                block.append(f"MATCH ({var}:Metric {{uri: 'metric:{m_name}'}})")
                vars_and_values.append((var, m_val))

            for j, (var, m_val) in enumerate(vars_and_values):
                suffix = ";" if j == len(vars_and_values) - 1 else ""
                block.append(
                    f"CREATE (col)-[:HAS_QUALITY_MEASUREMENT]->"
                    f"(:QualityMeasurement {{value: {cypher_value(m_val)}, dcatType: 'dqv:QualityMeasurement'}})"
                    f"-[:ON_METRIC]->({var}){suffix}"
                )
                stats["measurements"] += 1

            block.append("")
            lines.extend(block)

            # Top values — only for columns where the profiler captured them
            top_values = col.get("top_values") or []
            if top_values:
                tv_block = [f"// Top values: {col_name}"]
                tv_block.append(f"MATCH (col:Column {{uri: '{col_uri}'}})")
                for j, tv in enumerate(top_values):
                    suffix = ";" if j == len(top_values) - 1 else ""
                    val = cypher_value(tv["value"])
                    count = int(tv["count"])
                    freq = float(tv.get("frequency", 0.0))
                    tv_block.append(
                        f"CREATE (col)-[:HAS_TOP_VALUE]->"
                        f"(:TopValue {{value: {val}, count: {count}, frequency: {cypher_value(freq)}}}){suffix}"
                    )
                    stats["top_value_nodes"] += 1
                tv_block.append("")
                lines.extend(tv_block)

    return lines, stats


def main():
    parser = argparse.ArgumentParser(
        description="Generate a DQV Cypher enrichment script from data-profiling YAML files.",
    )
    parser.add_argument(
        "yaml_dir",
        nargs="?",
        default=".",
        help="Directory containing *__*__profile.yaml files (default: .)",
    )
    parser.add_argument(
        "output_file",
        nargs="?",
        default=None,
        help="Output .cypher file path (default: <yaml_dir>/dqv_profile.cypher)",
    )
    parser.add_argument("--project-code", default=None, help="Project code for scoped URIs")
    args = parser.parse_args()

    yaml_dir = os.path.abspath(args.yaml_dir)
    cypher_dir = os.path.join(yaml_dir, "cypher_scripts")
    os.makedirs(cypher_dir, exist_ok=True)
    output_file = (
        os.path.abspath(args.output_file)
        if args.output_file
        else os.path.join(cypher_dir, "dqv_profile.cypher")
    )

    profiles = load_profiles(yaml_dir)
    pc = getattr(args, "project_code", None)
    lines, stats = build_cypher(profiles, project_code=pc)

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated: {output_file}")
    print(f"  Datasets (tables):    {stats['datasets']}")
    print(f"  Columns:              {stats['columns']}")
    print(f"  Quality measurements: {stats['measurements']}")
    print(f"  Top value nodes:      {stats['top_value_nodes']}")


if __name__ == "__main__":
    main()
