"""DQ test package assembly — downloadable packages for generated DQ test suites.

Mirrors the serving_package pattern: collect_dq_files() gathers the generated
test code (excluding per-run results/), assemble_dq_package() adds a README,
and the result is a {rel_path: text} map ready for zip_response().
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from .config import BASE_PROJECT_DIR
from .dq_test_executor import _FRAMEWORKS, dq_subdir

_SOURCE_MODES = ("catalog", "dprod")

_EXCLUDE_DIRS = {"results", "__pycache__", ".venv"}
_EXCLUDE_NAMES = {".env"}


# ── Per-framework README templates ────────────────────────────────────────────

def _readme_gx(project_code: str) -> str:
    return f"""\
# DQ Tests — Great Expectations ({project_code})

> A self-contained, runnable [Great Expectations](https://greatexpectations.io/) test
> suite generated by Data Workbench from the **approved quality rules** for
> **{project_code}**. Every expectation traces back to one rule on the knowledge graph.
> This is the same package Data Workbench runs when you click **Run DQ Tests** — download
> it, point it at your database, and run it anywhere (CI included) with no Workbench
> dependency.

## Artifact inventory

| File / dir | Purpose |
|---|---|
| `run_gx_validations.py` | **Entry point — this is what you run.** Builds the expectation suites, validates each table, and writes the results. |
| `requirements.txt` | Python deps (`great-expectations` + your database driver). |
| `expectations/` *(generated)* | The expectation-suite definitions — one suite per table, each expectation derived from an approved rule. |
| `README.md` | This document. |
| `results/` *(created on run)* | Per-run outputs — see [Outputs](#outputs). Excluded from the package until you run it. |

## How it works

```mermaid
flowchart LR
    R["Approved quality rules<br/>(knowledge graph)"] -->|generated once| S["expectations/<br/>(one suite per table)"]
    ENV["--conn-string / flags"] --> V["run_gx_validations.py"]
    S --> V
    V -->|validate each table| DB[("Your database<br/>tables or vw_* views")]
    V --> OUT["results/<br/>run_result.json + report.md"]
    style R fill:#eef2ff,stroke:#6366f1
    style OUT fill:#f0fdf4,stroke:#16a34a
```

## How the technology works

Great Expectations models data quality as **expectation suites** — named collections of
declarative checks (`expect_column_values_to_not_be_null`,
`expect_column_values_to_be_between`, `expect_column_values_to_be_in_set`, …). Data
Workbench compiles each **approved rule** into exactly one expectation, groups the
expectations by table into a suite, and the runner validates each table's suite against
live data using a SQL-backed datasource (no data is copied — GX pushes the checks down as
SQL). Each expectation's result carries the count and a sample of the *unexpected* values,
so a failure tells you not just **that** a rule broke but **which rows** broke it.

```mermaid
flowchart TD
    subgraph "per table"
      C["connect (SQLAlchemy)"] --> Q["run the table's<br/>expectation suite"]
      Q --> A{"all expectations<br/>pass?"}
      A -->|yes| P["record PASS"]
      A -->|no| F["record FAIL<br/>+ unexpected samples"]
    end
    P --> RR["aggregate → run_result.json + report.md"]
    F --> RR
    RR --> X{"any table failed?"}
    X -->|yes| NZ["exit non-zero (CI gate)"]
    X -->|no| Z["exit 0"]
    style F fill:#fef2f2,stroke:#dc2626
    style Z fill:#f0fdf4,stroke:#16a34a
```

## Configuration

| Flag / env | Required | Description |
|---|---|---|
| `--conn-string` | yes | SQLAlchemy connection string for the database to test (e.g. `postgresql://user:pass@host:5432/db`). |
| `--sample-limit` | no | Cap rows scanned per table (faster smoke run). Omit to validate the full table. |
| `--output-dir` | no | Where to write `results/` (default `results/`). |

Secrets ride the process/CLI only — nothing is written to disk beyond the results you ask for.

## Usage

```bash
pip install -r requirements.txt
python run_gx_validations.py --conn-string "<your-connection-string>"
# full data by default; add --sample-limit 5000 for a quick smoke run
python run_gx_validations.py --conn-string "<...>" --sample-limit 5000
```

The process **exits non-zero when any expectation fails**, so it drops straight into a CI gate.

## Outputs

Every run writes three files into the output directory (`results/` by default):

| File | Purpose |
|---|---|
| `run_result.json` | **Machine-readable verdict** (the v1 `run_result.json` contract shared with the serving packages): `status` (`success`/`failed`), per-table `steps`, and `metrics` (tables, expectations passed/failed, `tables_failed`). Parse this in CI. |
| `report.md` | **Human-readable report**: overall PASS/FAIL, a per-table pass/fail table, and each failed expectation with its unexpected sample values. |
| `gx_results_<timestamp>.json` | The full framework-native GX result log (kept per-run for history). |

### Load results back into Data Workbench

Re-run the **Run DQ Tests** stage from the UI or via the MCP `run_stage` tool — it
re-executes the suite and loads the latest results back into the graph automatically.
"""


def _readme_python(project_code: str) -> str:
    return f"""\
# DQ Tests — Pure Python / Pandera ({project_code})

> A self-contained, runnable [Pandera](https://pandera.readthedocs.io/) test suite
> generated by Data Workbench from the **approved quality rules** for **{project_code}**.
> Every check traces back to one rule on the knowledge graph. This is the same package
> Data Workbench runs when you click **Run DQ Tests** — download it, point it at your
> database, and run it anywhere (CI included) with no Workbench dependency.

## Artifact inventory

| File / dir | Purpose |
|---|---|
| `run_all.py` | **Entry point — this is what you run.** Loads each table, applies its validator, and writes the results. |
| `validators/` | One Python validator per table — a Pandera `DataFrameSchema` whose column checks are compiled from the approved rules. |
| `requirements.txt` | Python deps (`pandera` + `pandas` + your database driver). |
| `README.md` | This document. |
| `data_quality_results/` *(created on run)* | Per-run outputs — see [Outputs](#outputs). Excluded from the package until you run it. |

## How it works

```mermaid
flowchart LR
    R["Approved quality rules<br/>(knowledge graph)"] -->|generated once| S["validators/<br/>(one DataFrameSchema per table)"]
    ENV["--conn-string / flags"] --> V["run_all.py"]
    S --> V
    V -->|load + validate each table| DB[("Your database<br/>tables or vw_* views")]
    V --> OUT["data_quality_results/<br/>run_result.json + report.md"]
    style R fill:#eef2ff,stroke:#6366f1
    style OUT fill:#f0fdf4,stroke:#16a34a
```

## How the technology works

Pandera validates a **DataFrame against a schema**: each `validators/<table>.py` declares a
`DataFrameSchema` whose per-column `Check`s are compiled one-to-one from the approved rules
(not-null, ranges, allowed value sets, regex, uniqueness, …). The runner reads each table
into a pandas DataFrame and validates it in `lazy=True` mode, so **all** failing checks are
collected in one pass (not just the first). Each rule carries a **severity**: a
`sh:Violation` failure fails the run (exit non-zero), while a `sh:Warning` failure is
reported but does not fail — so you can ship advisory checks alongside hard gates.

```mermaid
flowchart TD
    subgraph "per table"
      L["load table → DataFrame"] --> Q["schema.validate(df, lazy=True)"]
      Q --> A{"failing checks?"}
      A -->|none| P["record PASS"]
      A -->|violation| F["record FAIL"]
      A -->|warning only| W["record WARN (non-fatal)"]
    end
    P --> RR["aggregate → run_result.json + report.md"]
    F --> RR
    W --> RR
    RR --> X{"any violation failed?"}
    X -->|yes| NZ["exit non-zero (CI gate)"]
    X -->|no| Z["exit 0"]
    style F fill:#fef2f2,stroke:#dc2626
    style W fill:#fffbeb,stroke:#b45309
    style Z fill:#f0fdf4,stroke:#16a34a
```

## Configuration

| Flag / env | Required | Description |
|---|---|---|
| `--conn-string` | yes | SQLAlchemy connection string for the database to test (e.g. `postgresql://user:pass@host:5432/db`). |
| `--sample-limit` | no | Cap rows loaded per table (faster smoke run). Omit to validate the full table. |
| `--output-dir` | no | Where to write `data_quality_results/` (default `data_quality_results/`). |

Secrets ride the process/CLI only — nothing is written to disk beyond the results you ask for.

## Usage

```bash
pip install -r requirements.txt
python run_all.py --conn-string "<your-connection-string>"
# full data by default; add --sample-limit 5000 for a quick smoke run
python run_all.py --conn-string "<...>" --sample-limit 5000
```

A `sh:Violation` failure **exits the process non-zero**, so `run_all.py` works as a CI gate;
`sh:Warning` failures are reported but keep the exit code 0.

## Outputs

Every run writes three files into the output directory (`data_quality_results/` by default):

| File | Purpose |
|---|---|
| `run_result.json` | **Machine-readable verdict** (the v1 `run_result.json` contract shared with the serving packages): `status` (`success`/`failed`), per-table `steps`, and `metrics` (checks passed/failed/errored, `violations_failed`, `warnings_failed`, `tables_failed`). Parse this in CI. |
| `report.md` | **Human-readable report**: overall PASS/FAIL, a per-table pass/fail/error table, and each failed check with its severity + detail. |
| `dq_results_<timestamp>.json` | The full per-check result log (kept per-run for history). |

### Load results back into Data Workbench

Re-run the **Run DQ Tests** stage from the UI or via the MCP `run_stage` tool — it
re-executes the suite and loads the latest results back into the graph automatically.
"""


_README_BUILDERS = {
    "gx": _readme_gx,
    "pandera": _readme_python,
}


# ── Detection + collection ────────────────────────────────────────────────────

def detect_active_framework(project_code: str, source_mode: str = "catalog") -> Optional[str]:
    """Return the active DQ framework name ('gx' or 'pandera') by checking which
    generated entry-point script exists on disk for the given ``source_mode``
    (catalog → ``dq_tests_*``; dprod → ``dq_tests_*_dprod``). Returns None when no
    test suite has been generated yet for that mode."""
    project_dir = BASE_PROJECT_DIR / project_code
    for fw in _FRAMEWORKS:
        script = project_dir / dq_subdir(fw["subdir"], source_mode) / fw["script"]
        if script.exists():
            return fw["framework"]
    return None


def available_dq_suites(project_code: str) -> list[dict]:
    """Enumerate the generated DQ suites present on disk, across both modes.

    Returns a list of ``{"framework", "source_mode"}`` for every framework whose
    entry-point script exists. A `dpe-sa` product can hold both a catalog and a
    dprod suite; a `dpe-cf` product only ever has the dprod one. dprod is listed
    first so callers that need a single default treat the product suite as primary.
    """
    project_dir = BASE_PROJECT_DIR / project_code
    suites: list[dict] = []
    for mode in ("dprod", "catalog"):
        for fw in _FRAMEWORKS:
            script = project_dir / dq_subdir(fw["subdir"], mode) / fw["script"]
            if script.exists():
                suites.append({"framework": fw["framework"], "source_mode": mode})
    return suites


def resolve_suite(project_code: str, source_mode: Optional[str] = None) -> tuple[Optional[str], Optional[str]]:
    """Pick a (framework, source_mode) suite for a reader/download.

    Honors an explicit ``source_mode`` when that suite exists; otherwise falls back
    to whatever is present (dprod preferred — the product suite is primary). Returns
    ``(None, None)`` when nothing has been generated yet.
    """
    suites = available_dq_suites(project_code)
    if not suites:
        return None, None
    if source_mode:
        match = next((s for s in suites if s["source_mode"] == source_mode), None)
        if match:
            return match["framework"], match["source_mode"]
    chosen = suites[0]  # available_dq_suites lists dprod first
    return chosen["framework"], chosen["source_mode"]


def collect_dq_files(
    project_code: str,
    framework: Optional[str] = None,
    source_mode: str = "catalog",
) -> dict[str, str]:
    """Collect generated DQ test files into a {rel_path: text} map.

    Excludes ``results/`` (per-run output) and cache dirs. Returns an empty dict
    when no test files exist yet. ``framework`` defaults to auto-detection from disk
    within the given ``source_mode``'s subdir.
    """
    if framework is None:
        framework = detect_active_framework(project_code, source_mode)
    if framework is None:
        return {}

    fw_meta = next((f for f in _FRAMEWORKS if f["framework"] == framework), None)
    if fw_meta is None:
        return {}

    test_dir = BASE_PROJECT_DIR / project_code / dq_subdir(fw_meta["subdir"], source_mode)
    if not test_dir.exists():
        return {}

    files: dict[str, str] = {}
    for p in sorted(test_dir.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(test_dir)
        if any(part in _EXCLUDE_DIRS for part in rel.parts):
            continue
        if p.name in _EXCLUDE_NAMES:
            continue
        try:
            files[str(rel)] = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            pass  # skip unreadable / binary files silently
    return files


def assemble_dq_package(
    project_code: str,
    framework: Optional[str] = None,
    source_mode: str = "catalog",
) -> Optional[dict[str, str]]:
    """Assemble a downloadable DQ test package: test files + README.

    Returns None when no generated test files exist yet.
    Returns a {rel_path: text} map for use with serving_package.zip_response().
    """
    if framework is None:
        framework = detect_active_framework(project_code, source_mode)
    if framework is None:
        return None

    files = collect_dq_files(project_code, framework, source_mode)
    if not files:
        return None

    readme_builder = _README_BUILDERS.get(framework)
    if readme_builder and "README.md" not in files:
        readme = readme_builder(project_code)
        if source_mode == "dprod":
            readme += (
                "\n> **Product (dprod) suite** — these tests validate the "
                "**deployed product views** (`vw_*`) against the rules authored on "
                "the data contract (`:DProdColumn`), not the raw source tables. "
                "Point `--conn-string` at the deployed product target.\n"
            )
        files["README.md"] = readme

    return files
