steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _VITE_API_URL: ''
  _IMAGE: 'us-central1-docker.pkg.dev/eogwapq-agbg-internal-data-mig/bfsi-silver/frontend:v1.1'
options:
  logging: CLOUD_LOGGING_ONLY
