#!/usr/bin/env python3
"""
Generate a Cypher script from data-discovery YAML files using the W3C DCAT-2 ontology.

Usage:
    python generate_cypher.py [yaml_dir] [output_file] [--project-code CODE]

    yaml_dir      - directory containing <schema>__<table>.yaml files (default: .)
    output_file   - path for the output .cypher file (default: <yaml_dir>/catalog.cypher)
    --project-code - project code for graph-level isolation via :Project node
"""

import sys
import os
import glob
import argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def esc(value: str) -> str:
    """Escape single quotes for Cypher string literals."""
    return str(value).replace("'", "\\'")


def load_tables(yaml_dir: str) -> list[dict]:
    """Load all metadata YAML files, excluding profile files."""
    # Look in data_discovery/ subfolder first, fall back to yaml_dir itself
    discovery_subdir = os.path.join(yaml_dir, "data_discovery")
    search_dir = discovery_subdir if os.path.isdir(discovery_subdir) else yaml_dir

    pattern = os.path.join(search_dir, "*.yaml")
    files = sorted(glob.glob(pattern))
    metadata_files = [f for f in files if "__profile" not in os.path.basename(f)]

    if not metadata_files:
        print(
            f"ERROR: No data-discovery YAML files found in '{search_dir}'.\n"
            "Expected files matching <schema>__<table>.yaml",
            file=sys.stderr,
        )
        sys.exit(1)

    tables = []
    for f in metadata_files:
        with open(f) as fh:
            data = yaml.safe_load(fh)
        if data and "schema" in data and "table" in data:
            tables.append(data)
        else:
            print(f"WARNING: Skipping '{f}' — missing 'schema' or 'table' field.", file=sys.stderr)

    return tables


def _uri(prefix: str, path: str, project_code: str | None = None) -> str:
    """Build a URI with optional project-code scoping: prefix:project_code:path or prefix:path."""
    if project_code:
        return f"{prefix}:{esc(project_code)}:{path}"
    return f"{prefix}:{path}"


def build_cypher(tables: list[dict], project_code: str | None = None) -> tuple[list[str], dict]:
    """Build Cypher MERGE statements and return lines + stats."""
    lines = []
    stats = {"schemas": set(), "datasets": 0, "columns": 0, "fk_rels": 0}

    # ── Header ──────────────────────────────────────────────────────────────
    lines += [
        "// DCAT-2 Knowledge Graph",
        "// Ontology: https://www.w3.org/TR/vocab-dcat-2/",
        "// Generated by the dcat-neo4j Claude skill",
    ]
    if project_code:
        lines.append(f"// Project: {project_code}")
    lines.append("")

    # Group tables by schema to know which Catalogs to create
    schemas: dict[str, list[dict]] = {}
    for t in tables:
        schemas.setdefault(t["schema"], []).append(t)
    stats["schemas"] = set(schemas.keys())

    # ── Project node (if project_code provided) ────────────────────────────
    if project_code:
        lines.append("// ── Project node " + "─" * 59)
        lines.append(
            f"MERGE (:Project {{projectCode: '{esc(project_code)}'}});"
        )
        lines.append("")

    pc = project_code  # shorthand

    # ── Catalogs (dcat:Catalog) ─────────────────────────────────────────────
    lines.append("// ── Catalogs (dcat:Catalog) " + "─" * 50)
    for schema in schemas:
        uri = _uri("catalog", esc(schema), pc)
        lines.append(
            f"MERGE (cat:Catalog {{uri: '{uri}'}}) "
            f"ON CREATE SET cat.name = '{esc(schema)}', cat.dcatType = 'dcat:Catalog';"
        )
    lines.append("")

    # ── Project → Catalog linking ──────────────────────────────────────────
    if pc:
        lines.append("// ── Project → Catalog relationships " + "─" * 40)
        for schema in schemas:
            uri = _uri("catalog", esc(schema), pc)
            lines.append(
                f"MATCH (prj:Project {{projectCode: '{esc(pc)}'}}), "
                f"(cat:Catalog {{uri: '{uri}'}})"
            )
            lines.append("MERGE (prj)-[:HAS_CATALOG]->(cat);")
        lines.append("")

    # ── Datasets (dcat:Dataset) ─────────────────────────────────────────────
    lines.append("// ── Datasets (dcat:Dataset) " + "─" * 50)
    for t in tables:
        schema, table = t["schema"], t["table"]
        uri = _uri("dataset", f"{esc(schema)}.{esc(table)}", pc)
        row_count = t.get("row_count")
        rc_prop = f", row_count: {row_count}" if row_count is not None else ""
        lines.append(
            f"MERGE (ds:Dataset {{uri: '{uri}'}}) "
            f"ON CREATE SET ds.name = '{esc(table)}', "
            f"ds.searchName = '{esc(table.lower())}', ds.schema = '{esc(schema)}', "
            f"ds.dcatType = 'dcat:Dataset'{rc_prop};"
        )
        stats["datasets"] += 1
    lines.append("")

    # ── Columns ─────────────────────────────────────────────────────────────
    lines.append("// ── Columns " + "─" * 65)
    for t in tables:
        schema, table = t["schema"], t["table"]
        pk_cols: set[str] = set()
        pk_info = t.get("primary_key") or {}
        if isinstance(pk_info, dict):
            pk_cols = set(pk_info.get("columns") or [])

        for col in t.get("columns") or []:
            col_name = col["name"]
            uri = _uri("column", f"{esc(schema)}.{esc(table)}.{esc(col_name)}", pc)
            data_type = esc(col.get("type") or "unknown")
            nullable = "true" if col.get("nullable", True) else "false"
            is_pk = "true" if col_name in pk_cols else "false"
            ordinal = col.get("ordinal", 0)
            lines.append(
                f"MERGE (col:Column {{uri: '{uri}'}}) "
                f"ON CREATE SET col.name = '{esc(col_name)}', "
                f"col.searchName = '{esc(col_name.lower())}', "
                f"col.dataType = '{data_type}', col.nullable = {nullable}, "
                f"col.primaryKey = {is_pk}, col.ordinal = {ordinal};"
            )
            stats["columns"] += 1
    lines.append("")

    # ── Catalog → Dataset (dcat:dataset) ────────────────────────────────────
    lines.append("// ── Catalog → Dataset relationships (dcat:dataset) " + "─" * 26)
    for t in tables:
        schema, table = t["schema"], t["table"]
        cat_uri = _uri("catalog", esc(schema), pc)
        ds_uri = _uri("dataset", f"{esc(schema)}.{esc(table)}", pc)
        lines.append(
            f"MATCH (cat:Catalog {{uri: '{cat_uri}'}}), (ds:Dataset {{uri: '{ds_uri}'}})"
        )
        lines.append("MERGE (cat)-[:DCAT_DATASET]->(ds);")
    lines.append("")

    # ── Dataset → Column ────────────────────────────────────────────────────
    lines.append("// ── Dataset → Column relationships " + "─" * 41)
    for t in tables:
        schema, table = t["schema"], t["table"]
        ds_uri = _uri("dataset", f"{esc(schema)}.{esc(table)}", pc)
        for col in t.get("columns") or []:
            col_uri = _uri("column", f"{esc(schema)}.{esc(table)}.{esc(col['name'])}", pc)
            lines.append(
                f"MATCH (ds:Dataset {{uri: '{ds_uri}'}}), (col:Column {{uri: '{col_uri}'}})"
            )
            lines.append("MERGE (ds)-[:HAS_COLUMN]->(col);")
    lines.append("")

    # ── Foreign Key relationships (dct:relation) ─────────────────────────────
    # Dataset-level :REFERENCES edges (table-to-table) plus column-level
    # :FK_REFERENCES edges (column-to-column) so an ERD viewer can route an
    # edge between the specific FK and PK columns participating in each FK.
    lines.append("// ── Foreign Key relationships (dct:relation) " + "─" * 32)
    for t in tables:
        schema, table = t["schema"], t["table"]
        ds_uri = _uri("dataset", f"{esc(schema)}.{esc(table)}", pc)
        for fk in t.get("foreign_keys") or []:
            ref_schema = fk.get("referenced_schema") or schema
            ref_table = fk["referenced_table"]
            ref_uri = _uri("dataset", f"{esc(ref_schema)}.{esc(ref_table)}", pc)
            constraint = esc(fk.get("constraint_name", ""))
            on_delete = esc(fk.get("on_delete") or "NO ACTION")
            on_update = esc(fk.get("on_update") or "NO ACTION")
            fk_cols = fk.get("columns") or []
            ref_fk_cols = fk.get("referenced_columns") or []
            cols = esc(", ".join(fk_cols))
            ref_cols = esc(", ".join(ref_fk_cols))
            lines.append(
                f"MATCH (ds1:Dataset {{uri: '{ds_uri}'}}), (ds2:Dataset {{uri: '{ref_uri}'}})"
            )
            lines.append(
                f"MERGE (ds1)-[:REFERENCES {{constraintName: '{constraint}', "
                f"columns: '{cols}', referencedColumns: '{ref_cols}', "
                f"onDelete: '{on_delete}', onUpdate: '{on_update}'}}]->(ds2);"
            )
            stats["fk_rels"] += 1
            # Column-level edges: pair-wise FK col → referenced col.
            for src_col, ref_col in zip(fk_cols, ref_fk_cols):
                src_col_uri = _uri("column", f"{esc(schema)}.{esc(table)}.{esc(src_col)}", pc)
                ref_col_uri = _uri("column", f"{esc(ref_schema)}.{esc(ref_table)}.{esc(ref_col)}", pc)
                lines.append(
                    f"MATCH (c1:Column {{uri: '{src_col_uri}'}}), (c2:Column {{uri: '{ref_col_uri}'}})"
                )
                lines.append(
                    f"MERGE (c1)-[:FK_REFERENCES {{constraintName: '{constraint}'}}]->(c2);"
                )
    lines.append("")

    return lines, stats


def main():
    parser = argparse.ArgumentParser(
        description="Generate a Cypher script from data-discovery YAML files using the W3C DCAT-2 ontology.",
    )
    parser.add_argument(
        "yaml_dir",
        nargs="?",
        default=".",
        help="Directory containing <schema>__<table>.yaml files (default: .)",
    )
    parser.add_argument(
        "output_file",
        nargs="?",
        default=None,
        help="Output .cypher file path (default: <yaml_dir>/catalog.cypher)",
    )
    parser.add_argument("--project-code", default=None, help="Project code for graph-level isolation")
    args = parser.parse_args()

    yaml_dir = os.path.abspath(args.yaml_dir)
    cypher_dir = os.path.join(yaml_dir, "cypher_scripts")
    os.makedirs(cypher_dir, exist_ok=True)
    output_file = os.path.abspath(args.output_file) if args.output_file else os.path.join(cypher_dir, "catalog.cypher")

    tables = load_tables(yaml_dir)
    pc = getattr(args, "project_code", None)
    lines, stats = build_cypher(tables, project_code=pc)

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated: {output_file}")
    if pc:
        print(f"  Project:            {pc}")
    print(f"  Catalogs (schemas): {len(stats['schemas'])}  ({', '.join(sorted(stats['schemas']))})")
    print(f"  Datasets (tables):  {stats['datasets']}")
    print(f"  Columns:            {stats['columns']}")
    print(f"  FK relationships:   {stats['fk_rels']}")


if __name__ == "__main__":
    main()
